# render.yaml
services:
  - type: web
    name: eventstore
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn store.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: store.settings
      - key: PYTHON_VERSION
        value: 3.13.0
