# Generated by Django 5.1.6 on 2025-04-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bundle_images/')),
                ('products', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
