# Generated by Django 5.1.6 on 2025-04-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
