# Generated by Django 5.1.6 on 2025-04-30 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0002_remove_guest_phone_number_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='rsvp_status',
        ),
        migrations.AddField(
            model_name='guest',
            name='rsvp_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
