# Generated by Django 5.1.6 on 2025-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=255, unique=True),
        ),
    ]
